CREATE TABLE prices (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        brand_id BIGINT NOT NULL,
                        product_id BIGINT NOT NULL,
                        price_list INT NOT NULL,
                        priority INT NOT NULL,
                        start_date TIMESTAMP NOT NULL,
                        end_date TIMESTAMP NOT NULL,
                        price DECIMAL(10,2) NOT NULL,
                        currency VARCHAR(3) NOT NULL
);

CREATE INDEX idx_prices_search
    ON prices(product_id, brand_id, start_date, end_date, priority);